=== Darkyenus/Vincent/src/main/resources/public/questionnaire.dtd
<!--
All elements that present user-facing text are written in HTML, which means that it is possible to use formatting tags,
such as <i>italics</i>, <b>bold</b>, etc.
-->

<!ELEMENT questionnaire (title+, section+)>

<!ATTLIST questionnaire
        default-lang CDATA "en"
        >

<!ELEMENT title ANY>
<!ATTLIST title
        lang CDATA #IMPLIED
        always (true|false|yes|no) "false"
        >

<!ELEMENT section (title*, (info | question)*)>
<!ATTLIST section
        min-time CDATA "0"
        stage (always|only-first|except-first|only-last|except-last) "always"
        shown-wine (none|all|current) "current"
        >

<!ELEMENT info (title*, text*)>

<!ELEMENT text ANY>
<!ATTLIST text
        lang CDATA #IMPLIED
        >

<!ELEMENT question (title*, text*, (one-of, free-text, scale, time-progression))>
<!ATTLIST question
        id ID #REQUIRED
        required (true|false|yes|no) "true"
        >

<!ELEMENT one-of (category+ | option+)>
<!ELEMENT category (title*, option+)>

<!-- Actual constraint: (#PCDATA | (title+, detail*)) (not supported by DTD) -->
<!ELEMENT option (#PCDATA | title | detail)*>
<!ATTLIST option
        value CDATA #IMPLIED
        detail (true|false|yes|no) "false"
        detail-type (sentence|paragraph|number) "sentence"
        >

<!ELEMENT detail ANY>
<!ATTLIST detail
        lang CDATA #IMPLIED
        >

<!ELEMENT free-text (placeholder*)>
<!ATTLIST free-text
        type (sentence|paragraph|number) "sentence"
        >

<!ELEMENT placeholder ANY>
<!ATTLIST placeholder
        lang CDATA #IMPLIED
        >

<!ELEMENT scale (min, max)?>
<!ATTLIST scale
        min CDATA "1"
        max CDATA "7">

<!-- Actual constraint: (#PCDATA | title+) (not supported by DTD) -->
<!ELEMENT min (#PCDATA | title)*>
<!ELEMENT max (#PCDATA | title)*>

<!ELEMENT time-progression (one-of | scale)>
<!ATTLIST time-progression
        interval CDATA #REQUIRED
        repeats CDATA #REQUIRED
        >

=== Darkyenus/Vincent/resources/docs/questionnaire-example-wine-sheet.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE questionnaire PUBLIC "-//UNIBZ//Vincent Questionnaire Template 1.0//EN" "vincent://questionnaire.dtd">
<questionnaire>
    <title>Wine Questionnaire</title>

    <section stage="except-first" min-time="60" shown-wine="all">
        <info>
            <text>Cleanse your palate before continuing to the next wine.</text>
        </info>
        <question id="feedback" required="false">
            <title>Feedback</title>
            <text>While you are waiting, feel free to share any feedback you might have.</text>
            <free-text type="paragraph"/>
        </question>
    </section>

    <section>
        <title>Visual evaluation</title>

        <question id="clarity">
            <title>Clarity</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="color-tonality">
            <title>Color tonality</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="effervescence">
            <title>Effervescence</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>
    </section>

    <section>
        <title>Olfactory evaluation</title>
        <question id="overall-intensity">
            <title>Overall intensity</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="olfactory-floral">
            <title><i>Floral</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="olfactory-tree-fruit-apple">
            <title><i>Tree fruit (apple)</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="olfactory-tree-fruit-pear">
            <title><i>Tree fruit (pear)</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="olfactory-tropical-fruit">
            <title><i>Tropical fruit</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="olfactory-dried-fruit">
            <title><i>Dried fruit</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="olfactory-fresh-vegetative">
            <title><i>Fresh vegetative</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="olfactory-spicy">
            <title><i>Spicy</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="olfactory-cleanness">
            <title>Cleanness</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="unpleasant-odors">
            <title>Unpleasant odors</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>
    </section>

    <section>
        <title>Gustatory evaluation</title>
        <question id="warmness">
            <title>Warmness</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>
        <question id="sweetness">
            <title>Sweetness</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>
        <question id="sourness">
            <title>Sourness</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>
        <question id="salty-sapidity">
            <title>Salty/Sapidity</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>
        <question id="bitterness">
            <title>Bitterness</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>
        <question id="tannicity-astringency">
            <title>Tannicity/Astringency</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>
        <question id="gustatory-floral">
            <title><i>Floral</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="gustatory-tree-fruit-apple">
            <title><i>Tree fruit (apple)</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="gustatory-tree-fruit-pear">
            <title><i>Tree fruit (pear)</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="gustatory-tropical-fruit">
            <title><i>Tropical fruit</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="gustatory-dried-fruit">
            <title><i>Dried fruit</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="gustatory-fresh-vegetative">
            <title><i>Fresh vegetative</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="gustatory-spicy">
            <title><i>Spicy</i></title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="gustatory-cleanness">
            <title>Cleanness</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>

        <question id="unpleasant-flavors">
            <title>Unpleasant flavors</title>
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>
    </section>

    <section>
        <title>Overall quality judgement</title>

        <question id="overall-quality">
            <scale max="9"><min>Weak</min><max>Strong</max></scale>
        </question>
    </section>

    <section stage="only-last" shown-wine="none">
        <title>Goodbye</title>
        <info>
            <text>Thank you for your participation.</text>
        </info>
    </section>
</questionnaire>

=== Darkyenus/Vincent/docs/questionnaire-example.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE questionnaire PUBLIC "-//UNIBZ//Vincent Questionnaire Template 1.0//EN" "vincent://questionnaire.dtd">
<questionnaire default-lang="en">
    <title>Wine Questionnaire</title>
    <title lang="de">Wein Fragebogen</title>
    <title lang="it">Questionario sul vino</title>
    <title lang="cs">Dotazn√≠k o v√≠nƒõ</title>

    <section stage="only-first" shown-wine="all">
        <title>Welcome</title>
        <title lang="cs">V√≠tejte</title>

        <info>
            <text>
                This is an example questionnaire.
                This is a <a href="https://darkyen.com">clickable link</a>.
                Emoji test: üßê
            </text>
            <text lang="cs">
                Toto je uk√°zkov√Ω dotazn√≠k.
                Toto je <a href="https://darkyen.com">klikateln√Ω odkaz</a>.
                Test emoji: ü§®
            </text>
        </info>
    </section>

    <section stage="except-first" min-time="60" shown-wine="all">
        <info>
            <text>Cleanse your palate before continuing to the next wine.</text>
        </info>
        <question id="feedback" required="false">
            <title>Feedback</title>
            <text>While you are waiting, feel free to share any feedback you might have.</text>
            <free-text type="paragraph"/>
        </question>
    </section>

    <section>
        <title>Appearance</title>
        <title lang="de">Aussehen</title>
        <title lang="it">Aspetto</title>
        <title lang="cs">Vzhled</title>

        <question id="clarity">
            <title>Clarity</title>
            <one-of>
                <option value="sediments">
                    <title>Presence of sediments</title>
                </option>
                <option value="no-sediments">
                    <title>Absence of sediments</title>
                </option>
            </one-of>
        </question>

        <question id="color-tonality">
            <title>Color <i>tonality</i></title>
            <one-of>
                <category>
                    <title>White</title>
                    <option>Lemon</option>
                    <option>Yellow</option>
                    <option>Gold</option>
                    <option>Amber</option>
                </category>
                <category>
                    <title>Ros√®</title>
                    <option>Pink</option>
                    <option>Salmon</option>
                    <option>Copper</option>
                </category>
                <category>
                    <title>Red</title>
                    <option>Purple</option>
                    <option>Ruby</option>
                    <option>Garnet</option>
                    <option>Tawny</option>
                </category>
            </one-of>
        </question>

        <question id="color-intensity">
            <title>Color <i>intensity</i></title>
            <scale min="1" max="5">
                <min>Pale</min>
                <max>Deep</max>
            </scale>
        </question>

        <question id="fluidity">
            <title>Fluidity</title>
            <scale min="1" max="5">
                <min>Low</min>
                <max>High</max>
            </scale>
        </question>
    </section>

    <section>
        <title>Nose</title>
        <title lang="de">Nase</title>
        <title lang="it">Naso</title>
        <title lang="cs">Nos</title>

        <question id="nose-condition">
            <title>Condition</title>
            <one-of>
                <option>No fault</option>
                <option>
                    <title>With fault</title>
                    <detail>Faults/Taints</detail>
                </option>
            </one-of>
        </question>

        <question id="intensity">
            <title>Intensity</title>
            <scale min="1" max="5">
                <min>Low</min>
                <max>High</max>
            </scale>
        </question>

        <!-- TODO Replace with optional aroma tree -->
        <question id="aromas">
            <title>Aromas</title>
            <free-text/>
        </question>

        <question id="complexity">
            <title>Complexity</title>
            <scale min="1" max="5">
                <min>Low</min>
                <max>High</max>
            </scale>
        </question>
    </section>

    <section>
        <title>Palate</title>
        <title lang="de">Gaumen</title>
        <title lang="it">Palato</title>
        <title lang="cs">Chu≈•</title>

        <question id="body">
            <title>Body</title>
            <scale min="1" max="5">
                <min>Low</min>
                <max>High</max>
            </scale>
        </question>

        <question id="alcohol">
            <title>Alcohol</title>
            <scale min="1" max="5">
                <min>Low</min>
                <max>High</max>
            </scale>
        </question>

        <question id="sweetness">
            <title>Sweetness</title>
            <one-of>
                <option value="1">Not sweet</option>
                <option value="2">Sweet</option>
                <option value="3">Very sweet</option>
            </one-of>
        </question>

        <question id="acidity">
            <title>Acidity</title>
            <scale min="1" max="5">
                <min>Low</min>
                <max>High</max>
            </scale>
        </question>

        <question id="astringency">
            <title>Astringency</title>
            <scale min="1" max="5">
                <min>Low</min>
                <max>High</max>
            </scale>
        </question>

        <question id="balance">
            <title>Balance</title>
            <one-of>
                <option value="no">Unbalanced</option>
                <option value="yes">Well-Balanced</option>
            </one-of>
        </question>

        <question id="retronasal">
            <title>Retronasal</title>
            <free-text/>
        </question>

        <question id="length/finish">
            <title>Length/Finish</title>
            <one-of>
                <option value="1">Short</option>
                <option value="2">Medium</option>
                <option value="3">Long</option>
            </one-of>
        </question>

        <question id="palate-condition">
            <title>Condition</title>
            <one-of>
                <option>No fault</option>
                <option>
                    <title>With fault</title>
                    <detail>Faults/Taints</detail>
                </option>
            </one-of>
        </question>
    </section>

    <section>
        <title>Overall quality</title>
        <question id="overall-quality">
            <one-of>
                <option>Poor</option>
                <option>Acceptable</option>
                <option>Good</option>
                <option>Very Good</option>
                <option>Outstanding</option>
            </one-of>
        </question>
    </section>

    <section stage="only-last" shown-wine="none">
        <title>Goodbye</title>
        <info>
            <text>Thank you for your participation.</text>
        </info>
    </section>
</questionnaire>

=== Darkyenus/Vincent/resources/docs/questionnaire-example-time-progression.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE questionnaire PUBLIC "-//UNIBZ//Vincent Questionnaire Template 1.0//EN" "vincent://questionnaire.dtd">
<questionnaire>
    <title>Time-gated Wine Taste Survey</title>

    <section stage="only-first" shown-wine="all">
        <title>Welcome</title>

        <info>
            <text>
                In the following test, you will evaluate the wine taste as it evolves over time.
                Do not drink until prompted to and then try to answer each question as soon as it appears,
                with the response that is appropriate at the time of response.
                If you don't manage to respond in the given time limit, just continue as if nothing had happened,
                it will not prevent you from continuing. Nevertheless, please try to respond to all questions.
            </text>
        </info>

        <question id="example" required="false">
            <title>Practice example</title>
            <text>
                This is just an example! You can practise answering time-gated questions here, but <b>do not drink any wine </b> prior.
                This is not a part of the evaluation.
            </text>
            <time-progression interval="10" repeats="4">
                <one-of>
                    <option>Good</option>
                    <option>Mediocre</option>
                    <option>Bad</option>
                </one-of>
            </time-progression>
        </question>
    </section>

    <section stage="except-first" min-time="60" shown-wine="all">
        <info>
            <text>Cleanse your palate before continuing to the next wine.</text>
        </info>
        <question id="feedback" required="false">
            <title>Feedback</title>
            <text>While you are waiting, feel free to share any feedback you might have.</text>
            <free-text type="paragraph"/>
        </question>
    </section>

    <section>
        <title>Evaluation</title>

        <question id="evaluation">
            <title>Taste over time</title>
            <time-progression interval="5" repeats="6">
                <scale min="-5" max="5">
                    <min>Bad</min>
                    <max>Good</max>
                </scale>
            </time-progression>
        </question>
    </section>

    <section stage="only-last" shown-wine="none">
        <title>Goodbye</title>
        <info>
            <text>Thank you for your participation.</text>
        </info>
    </section>
</questionnaire>
